=== bednarekpiotr/PCK/Zadanie_3/księgarnia_v1.3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:typ="http://www.example.org/typyNasze"
targetNamespace="http://www.example.org/typyNasze" 
 elementFormDefault="qualified">

    <xs:complexType name="KsięgarniaTyp">
      <xs:sequence>
        <xs:element ref="typ:autorzy_książek"/>
        <xs:element ref="typ:lista_kategorii"/>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="typ:książka"/>
          <xs:element ref="typ:e-book"/>
          <xs:element ref="typ:czasopismo"/>
        </xs:choice>
        <xs:element ref="typ:metadane"/>
      </xs:sequence>
    </xs:complexType>
	
	<xs:simpleType name="IDAutorTyp">
			<xs:restriction base="xs:token">
				<xs:pattern value="[A-Z][A-Z][A-Z]?"/>
			</xs:restriction>
	</xs:simpleType>

  <xs:element name="księgarnia" type="typ:KsięgarniaTyp">
	<xs:key name="IdAutorKey">
		<xs:selector xpath="typ:autorzy_książek/typ:autor"/>
		<xs:field xpath="@IdAutora" />
	</xs:key>

	<xs:keyref name = "IdAutorKeyRef" refer = "typ:IdAutorKey" >
		<xs:selector xpath="typ:książka | typ:e-book | typ:czasopismo"/>
		<xs:field xpath="@IdAutora" />
	</xs:keyref>
	
	<xs:keyref name = "IdAutorDrugiKeyRef" refer = "typ:IdAutorKey" >
		<xs:selector xpath="typ:książka | typ:e-book | typ:czasopismo"/>
        <xs:field xpath="@IdAutoraDrugiego" />
	</xs:keyref>
  </xs:element>
   
  
  <xs:element name="autorzy_książek">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="typ:autor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
   <xs:element name="autor">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ:imięPierwsze"/>
        <xs:element minOccurs="0" ref="typ:imięDrugie"/>
        <xs:element ref="typ:nazwisko"/>
      </xs:sequence>
      <xs:attribute name="IdAutora" use="required" type="xs:ID"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="imięPierwsze">
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value = "[A-Z][a-z]*" />
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>  
  </xs:element>
  
  <xs:element name="imięDrugie" >
  <xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value = "[A-Z][a-z]*" />
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:element>
	
  <xs:element name="nazwisko">
   <xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value = "[A-Z][a-z]*(-[A-Z][a-z]*)?" />
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	</xs:element>
  
  
  
   <xs:element name="lista_kategorii">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="typ:definicja_kategorii"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
 
   <xs:element name="definicja_kategorii">
    <xs:complexType>
      <xs:attribute name="idKategorii" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[A-Z]*"/>
				<xs:maxLength value="10"/>
			</xs:restriction>
		</xs:simpleType>
	  </xs:attribute>
      <xs:attribute name="nazwa" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[A-Z][a-z]*"/>
				<xs:maxLength value="25"/>
			</xs:restriction>
		</xs:simpleType>
	 </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  
  
   <xs:element name="książka">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ:tytuł"/>
        <xs:element ref="typ:nazwa_kategorii"/>
        <xs:element ref="typ:język"/>
        <xs:element ref="typ:ISBN"/>
        <xs:element ref="typ:ilość_stron"/>
        <xs:element ref="typ:wydanie"/>
        <xs:element ref="typ:wydawnictwo"/>
        <xs:element ref="typ:cena"/>
        <xs:element ref="typ:opis"/>
      </xs:sequence>
      <xs:attribute name="pozycja_id" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="P[1-9][0-9]*"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	  </xs:attribute>	   
      <xs:attribute name="IdAutora" type="typ:IDAutorTyp" use="required" >
	</xs:attribute>
	<xs:attribute name="IdAutoraDrugiego" type="typ:IDAutorTyp" use="optional" >
	</xs:attribute>
      <xs:attribute name="autorzy" use="required"/>
    </xs:complexType>
  </xs:element>
  
 <xs:element name="e-book">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ:tytuł"/>
        <xs:element ref="typ:nazwa_kategorii"/>
        <xs:element ref="typ:język"/>
        <xs:element ref="typ:ISBN"/>
        <xs:element ref="typ:rozmiar"/>
        <xs:element ref="typ:wydanie"/>
        <xs:element ref="typ:wydawnictwo"/>
        <xs:element ref="typ:cena"/>
        <xs:element ref="typ:opis"/>
      </xs:sequence>
      <xs:attribute name="pozycja_id" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="P[1-9][0-9]*"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	  </xs:attribute>	   
      <xs:attribute name="IdAutora" type="typ:IDAutorTyp" use="required" >
	</xs:attribute>
	<xs:attribute name="IdAutoraDrugiego" type="typ:IDAutorTyp" use="optional" >
	</xs:attribute>
      <xs:attribute name="autorzy" use="required"/>
    </xs:complexType>
  </xs:element>
  
  
<xs:element name="czasopismo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ:tytuł"/>
        <xs:element ref="typ:nazwa_kategorii"/>
        <xs:element ref="typ:język"/>
        <xs:element ref="typ:ISBN"/>
        <xs:element ref="typ:częstotliwość"/>
        <xs:element ref="typ:wydanie"/>
        <xs:element ref="typ:wydawnictwo"/>
        <xs:element ref="typ:cena"/>
        <xs:element ref="typ:opis"/>
      </xs:sequence>
      <xs:attribute name="pozycja_id" use="required">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="P[1-9][0-9]*"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	  </xs:attribute>	   
      <xs:attribute name="IdAutora" type="typ:IDAutorTyp" use="required" >
	</xs:attribute>
	<xs:attribute name="IdAutoraDrugiego" type="typ:IDAutorTyp" use="optional" >
	</xs:attribute>
      <xs:attribute name="autorzy" use="required"/>
    </xs:complexType>
  </xs:element>
  
  
<xs:element name="tytuł">
	<xs:simpleType>
		<xs:restriction base="xs:string">
			<xs:maxLength value="300"/>
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="nazwa_kategorii" >
<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value="[A-Z][a-z]*"/>
			<xs:maxLength value="40"/>
		</xs:restriction>
	</xs:simpleType> 
</xs:element>

<xs:element name="język" >
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:enumeration value="polski"/>
			<xs:enumeration value="angielski"/>			
		</xs:restriction>
	</xs:simpleType>
  </xs:element>
  
<xs:element name="ISBN">
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9]{13}" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>	

<xs:element name="ilość_stron">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="99999" />
			<xs:minInclusive value= "1" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>


<xs:element name="rozmiar">
	<xs:simpleType>
		<xs:restriction base="xs:integer">
			<xs:maxInclusive value="9999" />
			<xs:minInclusive value= "1" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="częstotliwość">
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:enumeration value="dziennik" />
			<xs:enumeration value="tygodnik" />
			<xs:enumeration value="miesięcznik" />
			<xs:enumeration value="kwartalnik" />
			<xs:enumeration value="rocznik" />			
		</xs:restriction>
	</xs:simpleType>
</xs:element> 

<xs:element name="wydanie">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="typ:miejsce_wydania"/>
        <xs:element ref="typ:data_wydania"/>
      </xs:sequence>
	<xs:attribute name="numerWydania" type="xs:integer"/>
	</xs:complexType>
</xs:element> 
  
<xs:element name="miejsce_wydania">
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value="[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]*"/>
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>
<xs:element name="data_wydania">
	<xs:simpleType>
		<xs:restriction base="xs:date">
			<xs:maxInclusive value="2016-11-30" />
			<xs:minInclusive value= "1455-01-01" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="wydawnictwo" >
	<xs:simpleType>
		<xs:restriction base="xs:token">
			<xs:pattern value="[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]*( [A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]*)*"/>
			<xs:maxLength value="40" />
		</xs:restriction>
	</xs:simpleType>
</xs:element>

<xs:element name="cena">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:decimal">
					<xs:attribute name="waluta"  use="required">
						<xs:simpleType>
							<xs:restriction base="xs:token">
							<xs:enumeration value="PLN" />
							<xs:enumeration value="EUR" />
							<xs:enumeration value="GBP" />
							<xs:enumeration value="USD" />
							</xs:restriction>
							</xs:simpleType>
				</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>


<xs:element name="opis">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="1" ref="typ:opis_skrócony"/>
      </xs:sequence>
    </xs:complexType>
</xs:element>
  
<xs:element name="opis_skrócony" type="xs:string"/> 
  
<xs:element name="metadane">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="2" ref="typ:autor_projektu"/>
        <xs:element ref="typ:rok_akademicki"/>
      </xs:sequence>
    </xs:complexType>
</xs:element>

  <xs:element name="autor_projektu">
    <xs:complexType mixed="true">
      <xs:attribute name="indeks" default="195560">
        <xs:simpleType>
          <xs:restriction base="xs:token">
            <xs:enumeration value="195560"/>
            <xs:enumeration value="195627"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="rok_akademicki" default="2016/2017"/>
</xs:schema>

=== bednarekpiotr/PCK/Zadanie_4/księgarnia_v1.3_output.xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="księgarnia_v1.3_pomocniczy.xsl"?><księgarnia>
<!-- xmlns="http://www.example.org/typyNasze" -->
<!-- xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  -->
<!-- xsi:schemaLocation="http://www.example.org/typyNasze księgarnia_v1.3.xsd" > --> 
    
	
	<lista_kategorii>
		<kategoria>
			<nazwa>Psychologia</nazwa>
		</kategoria>
		<kategoria>
			<nazwa>Thriller</nazwa>
		</kategoria>
		<kategoria>
			<nazwa>Fantastyka</nazwa>
		</kategoria>
		<kategoria>
			<nazwa>Poradniki</nazwa>
		</kategoria>
	</lista_kategorii>
	
   
			<książka>
			    <!-- Rodzaje: książka, czasopismo, itp-->				
                <tytuł>Dziewczyna z pociągu</tytuł>
				<język>polski</język>
				<ISBN>9788380316904</ISBN>
				<ilość_stron>365</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Warszawa</miejsce_wydania>   
				    <data_wydania>2016-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Świat Książki</wydawnictwo>
                <cena waluta="USD">27.64</cena>
                
            <cenaPLN>110.56</cenaPLN>
		<Autorzy>
			<autor IdAutora="PH">
	<imięPierwsze>Paula</imięPierwsze>
	<nazwisko>Hawkins</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="PSYCH">
			<nazwa>Psychologia</nazwa>
		</kategoria>
	</książka>
			
			<książka>
			<tytuł>Ofiara losu</tytuł>
			<język>polski</język>
				<ISBN> 9788380154742</ISBN>
				<ilość_stron>587</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Warszawa</miejsce_wydania>   
				    <data_wydania>2016-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Czarna Owca</wydawnictwo>
                <cena waluta="PLN">18.68</cena>
                
            <cenaPLN>18.68</cenaPLN>
		<Autorzy>
			<autor IdAutora="CL">
	<imięPierwsze>Cmilla</imięPierwsze>
	<nazwisko>Christie</nazwisko>	
	</autor>
		</Autorzy>
		<kategoria IdKategorii="PSYCH">
			<nazwa>Psychologia</nazwa>
		</kategoria>
	</książka>
			
			<książka>
                <tytuł>Psychologia i życie</tytuł>
				<język>polski</język>
				<ISBN>9788301172572</ISBN>
				<ilość_stron>658</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Warszawa</miejsce_wydania>   
				    <data_wydania>2008-01-10</data_wydania>
				</wydanie>
                <wydawnictwo>Polskie Wwydawnictwo Naukowe</wydawnictwo>
                <cena waluta="PLN">107.28</cena>
                
            <cenaPLN>107.28</cenaPLN>
		<Autorzy>
			<autor IdAutora="PGZ">
	<imięPierwsze>Philip</imięPierwsze>
	<imięDrugie>G</imięDrugie>
	<nazwisko>Zimbardo</nazwisko>
	</autor>
			<autor IdAutora="RJG">
	<imięPierwsze>Richard</imięPierwsze>
	<imięDrugie>J</imięDrugie>
	<nazwisko>Gerrig</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="PSYCH">
			<nazwa>Psychologia</nazwa>
		</kategoria>
	</książka>
			
			<e-book>
			    <tytuł>Dopóki starczy światła</tytuł>
				<język>polski</język>
				<ISBN>9788324592821</ISBN>
				<rozmiar>35</rozmiar>
				<wydanie>
				    <miejsce_wydania>Wrocław</miejsce_wydania>   
				    <data_wydania>2012-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Dolnośląskie</wydawnictwo>
                <cena waluta="EUR">15.57</cena>
                
            <cenaPLN>70.065</cenaPLN>
		<Autorzy>
			<autor IdAutora="AC">
	<imięPierwsze>Agata</imięPierwsze>
	<nazwisko>Christie</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="PSYCH">
			<nazwa>Psychologia</nazwa>
		</kategoria>
	</e-book>
			
          	
			<czasopismo>
			    <tytuł>Montecristo</tytuł>
				<język>polski</język>
				<ISBN>9788380620896</ISBN>
				<częstotliwość>miesięcznik</częstotliwość>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2016-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Redis</wydawnictwo>
                <cena waluta="PLN">27.92</cena>
                
            <cenaPLN>27.92</cenaPLN>
		<Autorzy>
			<autor IdAutora="MS">
	<imięPierwsze>Martin</imięPierwsze>
	<nazwisko>Suter-Suter</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="POR">
			<nazwa>Poradniki</nazwa>
		</kategoria>
	</czasopismo>
			
			
			<e-book>
                <tytuł>Tajemnica Sittaford</tytuł>
				<język>polski</język>
				<ISBN>  9788324587933</ISBN>
				<rozmiar>85</rozmiar>
				<wydanie>
				    <miejsce_wydania>Wrocław</miejsce_wydania>   
				    <data_wydania>2010-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Dolnośląskie</wydawnictwo>
                <cena waluta="EUR">12.74</cena>
                
            <cenaPLN>57.33</cenaPLN>
		<Autorzy>
			<autor IdAutora="AC">
	<imięPierwsze>Agata</imięPierwsze>
	<nazwisko>Christie</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="PSYCH">
			<nazwa>Psychologia</nazwa>
		</kategoria>
	</e-book>			
    	
	
   
            
    
	
	
            <książka>
                <tytuł>Opowieści z Narnii Lew, Czarownica i stara szafa</tytuł>
				<język>polski</język>
				<ISBN>9788372781758</ISBN>
				<ilość_stron>225</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2016-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Media Rodzina</wydawnictwo>
                <cena waluta="PLN">14.26</cena>
                
            <cenaPLN>14.26</cenaPLN>
		<Autorzy>
			<autor IdAutora="CSL">
	<imięPierwsze>Cristian</imięPierwsze>
	<imięDrugie>S</imięDrugie>
	<nazwisko>Levis</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="FAN">
			<nazwa>Fantastyka</nazwa>
		</kategoria>
	</książka>
			<e-book>
                <tytuł>Ostatnia bitwa</tytuł>
				<język>polski</język>
				<ISBN>9788372788832</ISBN>
				<rozmiar>48</rozmiar>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2013-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Media Rodzina</wydawnictwo>
                <cena waluta="PLN">14.31</cena>
                
            <cenaPLN>14.31</cenaPLN>
		<Autorzy>
			<autor IdAutora="CSL">
	<imięPierwsze>Cristian</imięPierwsze>
	<imięDrugie>S</imięDrugie>
	<nazwisko>Levis</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="FAN">
			<nazwa>Fantastyka</nazwa>
		</kategoria>
	</e-book>
			<czasopismo>
                <tytuł>Książę Kaspian</tytuł>
				<język>polski</język>
				<ISBN>9788372788788</ISBN>
				<częstotliwość>tygodnik</częstotliwość>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2013-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Media Rodzina</wydawnictwo>
                <cena waluta="PLN">15.65</cena>
                
            <cenaPLN>15.65</cenaPLN>
		<Autorzy>
			<autor IdAutora="CSL">
	<imięPierwsze>Cristian</imięPierwsze>
	<imięDrugie>S</imięDrugie>
	<nazwisko>Levis</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="FAN">
			<nazwa>Fantastyka</nazwa>
		</kategoria>
	</czasopismo>
			<książka>
                <tytuł>Siostrzeniec Czarodzieja</tytuł>
				<język>polski</język>
				<ISBN>9788372788825</ISBN>
				<ilość_stron>259</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2013-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Media Rodzina</wydawnictwo>
                <cena waluta="PLN">14.31</cena>
                
            <cenaPLN>14.31</cenaPLN>
		<Autorzy>
			<autor IdAutora="CSL">
	<imięPierwsze>Cristian</imięPierwsze>
	<imięDrugie>S</imięDrugie>
	<nazwisko>Levis</nazwisko>
	</autor>
		</Autorzy>
		<kategoria IdKategorii="FAN">
			<nazwa>Fantastyka</nazwa>
		</kategoria>
	</książka>
			<książka>
                <tytuł>Lśnienie</tytuł>
				<język>polski</język>
				<ISBN>9788376488097</ISBN>
				<ilość_stron>259</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Warszawa</miejsce_wydania>   
				    <data_wydania>2015-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Prószyński Media</wydawnictwo>
                <cena waluta="USD">9.31</cena>
                
            <cenaPLN>37.24</cenaPLN>
		<Autorzy>
			<autor IdAutora="SK">
	<imięPierwsze>Stephen</imięPierwsze>
	<nazwisko>King</nazwisko>	
	</autor>
		</Autorzy>
		<kategoria IdKategorii="FAN">
			<nazwa>Fantastyka</nazwa>
		</kategoria>
	</książka>
    
	
	<książka>
	<tytuł>Dieta dla aktywnych</tytuł>
				<język>polski</język>
				<ISBN>9788364131165</ISBN>
				<ilość_stron>259</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2016-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Buk Rower</wydawnictwo>
                <cena waluta="PLN">25.50</cena>
                
	<cenaPLN>25.50</cenaPLN>
		<Autorzy>
			<autor IdAutora="LC">
	<imięPierwsze>Lorel</imięPierwsze>
	<nazwisko>Cordial</nazwisko>	
	</autor>
		</Autorzy>
		<kategoria IdKategorii="POR">
			<nazwa>Poradniki</nazwa>
		</kategoria>
	</książka>
		<książka>
				<tytuł>Jedz i trenuj</tytuł>
				<język>polski</język>
				<ISBN>9788364131172</ISBN>
				<ilość_stron>259</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Poznań</miejsce_wydania>   
				    <data_wydania>2015-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Buk Rower</wydawnictwo>
                <cena waluta="PLN">37.43</cena>
                
	<cenaPLN>37.43</cenaPLN>
		<Autorzy>
			<autor IdAutora="NC">
	<imięPierwsze>Nancy</imięPierwsze>
	<nazwisko>Clark</nazwisko>	
	</autor>
		</Autorzy>
		<kategoria IdKategorii="POR">
			<nazwa>Poradniki</nazwa>
		</kategoria>
	</książka>
	<książka>
				<tytuł>Pływanie dla każdego</tytuł>
				<język>polski</język>
				<ISBN>9788392638704</ISBN>
				<ilość_stron>259</ilość_stron>
				<wydanie>
				    <miejsce_wydania>Zielonka</miejsce_wydania>   
				    <data_wydania>2013-09-28</data_wydania>
				</wydanie>
                <wydawnictwo>Buk Rower</wydawnictwo>
                <cena waluta="PLN">21.56</cena>
                
	<cenaPLN>21.56</cenaPLN>
		<Autorzy>
			<autor IdAutora="TL">
